// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Higakinn/festival-crawler/app/cli_usecase"
	"github.com/Higakinn/festival-crawler/app/infrastructure/repository"
	"github.com/Higakinn/festival-crawler/cmd"
	"github.com/dstotijn/go-notion"
)

// Injectors from define.go:

func InitCLIUseCases(client *notion.Client, xClient *cmd.XClient, dbName string) *CLIUseCases {
	festivalRepository := repository.NewFestivalRepository(client, dbName)
	festivalUseCase := cli_usecase.NewFestivalUseCase(festivalRepository, xClient)
	cliUseCases := NewCLIUseCases(festivalUseCase)
	return cliUseCases
}
